#!/usr/bin/env python3
"""Generate a private, secret-safe .env.local for PLI local-v1.

The generated file is intentionally gitignored and chmod 600. The script prints
only paths and key presence metadata; it never prints generated secret values.
"""

from __future__ import annotations

import argparse
import os
import secrets
import shlex
from collections.abc import Mapping
from pathlib import Path

_SECRET_KEY_MARKERS = ("SECRET", "TOKEN", "PASSWORD", "DATABASE_URL", "PRIVATE", "KEY", "DSN")


def _default_repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _quote_env(value: str) -> str:
    return shlex.quote(value)


def build_env(repo_root: Path, *, secret_key: str | None = None, sqlcipher_key: str = "") -> dict[str, str]:
    """Build local-v1 env values using repo-local ignored runtime paths."""
    runtime_dir = repo_root.resolve() / ".pli-local-v1"
    return {
        "PLI_MODE": "local",
        "PLI_DEBUG": "false",
        "PLI_DEMO": "false",
        "PLI_SECRET_KEY": secret_key or secrets.token_urlsafe(64),
        "PLI_BASE_URL": "http://localhost:8000",
        "PLI_APP_URL": "http://localhost:5173",
        "PLI_CORS_ORIGINS": '["http://localhost:5173"]',
        "PLI_DB_PATH": str(runtime_dir / "db.sqlite"),
        "PLI_ATTACHMENTS_DIR": str(runtime_dir / "attachments"),
        # Optional but recommended before storing real email content locally.
        # Leave empty for the default local-v1 smoke path unless SQLCipher is installed.
        "PLI_SQLCIPHER_KEY": sqlcipher_key,
        # Real Gmail/Microsoft OAuth credentials are intentionally absent for local-v1.
        "PLI_GMAIL_CLIENT_ID": "",
        "PLI_GMAIL_CLIENT_SECRET": "",
        "PLI_GMAIL_REDIRECT_URI": "http://localhost:8000/auth/gmail/callback",
        "PLI_MS_CLIENT_ID": "",
        "PLI_MS_CLIENT_SECRET": "",
        "PLI_MS_REDIRECT_URI": "http://localhost:8000/auth/microsoft/callback",
        "PLI_MS_TENANT_ID": "common",
    }


def render_env(env: Mapping[str, str]) -> str:
    lines = [
        "# PLI local-v1 runtime generated by scripts/generate_local_v1_env.py",
        "# Secret-safe handling: keep this file local, gitignored, and chmod 600.",
        "# Do not paste generated values into tickets, chats, commits, or logs.",
        "",
    ]
    for key, value in env.items():
        lines.append(f"{key}={_quote_env(value)}")
    lines.append("")
    return "\n".join(lines)


def write_local_v1_env(
    repo_root: Path,
    *,
    env_path: Path | None = None,
    force: bool = False,
    secret_key: str | None = None,
    sqlcipher_key: str = "",
) -> Path:
    repo_root = repo_root.resolve()
    env_path = (env_path or repo_root / ".env.local").resolve()
    runtime_dir = repo_root / ".pli-local-v1"
    attachments_dir = runtime_dir / "attachments"
    runtime_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
    attachments_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
    os.chmod(runtime_dir, 0o700)
    os.chmod(attachments_dir, 0o700)

    flags = os.O_WRONLY | os.O_CREAT | (os.O_TRUNC if force else os.O_EXCL)
    env = build_env(repo_root, secret_key=secret_key, sqlcipher_key=sqlcipher_key)
    try:
        fd = os.open(env_path, flags, 0o600)
    except FileExistsError as exc:
        raise FileExistsError(f"{env_path} already exists; use --force to replace it") from exc
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write(render_env(env))
    os.chmod(env_path, 0o600)
    return env_path


def redact_for_summary(env: Mapping[str, str]) -> dict[str, str]:
    safe: dict[str, str] = {}
    for key, value in env.items():
        if any(marker in key.upper() for marker in _SECRET_KEY_MARKERS):
            safe[key] = "[SET]" if value else "[EMPTY]"
        else:
            safe[key] = value
    return safe


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate private .env.local for PLI local-v1")
    parser.add_argument("--repo-root", type=Path, default=_default_repo_root())
    parser.add_argument("--env-path", type=Path, default=None)
    parser.add_argument("--force", action="store_true", help="Replace an existing .env.local")
    args = parser.parse_args()

    env_path = write_local_v1_env(args.repo_root, env_path=args.env_path, force=args.force)
    env = build_env(args.repo_root.resolve())
    redacted = redact_for_summary(env)
    print(f"local-v1 env written: {env_path}")
    print("runtime directory prepared: " + str(args.repo_root.resolve() / ".pli-local-v1"))
    print("PLI_* keys (secret-safe):")
    for key, value in redacted.items():
        print(f"- {key}={value}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
